


restoredefaultpath();
% % in ---  folder 
addpath(genpath('C:\matRad'));



success =  moxunit_runtests(['C:' filesep 'matRad' filesep 'matRad' filesep 'unitTest' filesep 'matRad_moxunits'], ...
            '-with_coverage',... 
            '-cover',['C:' filesep 'matRad' filesep 'matRad' ],...
            '-cover_xml_file','coverage.xml',...
            '-cover_html_dir','coverage_html');       
%-----------------------------------------------------------------             
% profile on;
% 
% 
% moxunit_runtests ('C:\matRad\matRad\run_moxunits'); 
%  mocov('-cover','C:\matRad\matRad',...
%         '-profile_info',... 
%         '-cover_xml_file','coverage.xml',...
%         '-cover_html_dir','coverage_html');
%-------------------------------------------------------------------
     %   success =  moxunit_runtests('-cover_exclude', ['C:' filesep 'matRad' filesep 'matRad' filesep 'unitTest' filesep 'matRad_moxunits_tests' ], ['C:' filesep 'matRad' filesep 'matRad' filesep 'unitTest' filesep 'matRad_moxunits_tests' ] ,['C:' filesep 'matRad' filesep 'matRad' filesep 'unitTest' filesep 'optomization_tests_with_moxunits_tests' ], ...
%                     '-with_coverage',... 
%                     '-cover',['C:' filesep 'matRad' filesep 'matRad' filesep 'optimization' filesep 'DoseObjectives'],...
%                     '-cover_xml_file','coverage.xml',...
%                     '-cover_html_dir','coverage_html');



     

